### ISSUE TITLE
文件名称都变成请忽使用第三方工具,而且上传后显示完成在蓝奏云里又显示没有任何文件上传

### ISSUE THREAD

**Issue by Erocooocool** [chenhb23/lanzouyun-disk#101]
![SharedScreenshot](https://user-images.githubusercontent.com/101471737/213480274-d165cff0-9c19-4df7-a121-376b49e3565e.jpg)

**Comment by ppzhuya** [comment]
+1

**Comment by chenhb23** [comment]
已修复
