### ISSUE TITLE
软件无法正常打开

### ISSUE THREAD

**Issue by Olivia-K99** [chenhb23/lanzouyun-disk#11]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: E4483780-0B2A-4B1B-8628-ACDF7FAD0EB3
CrashReporter Key:   FA00274D-BC6B-EB3F-A21B-6EA520AC3294
Hardware Model:      MacBookPro15,4
Process:             蓝奏云盘 [1624]
Path:                /Applications/蓝奏云盘.app/Contents/MacOS/蓝奏云盘
Identifier:          org.chenhb23.lanzou
Version:             1.0.8 (1.0.8)
Code Type:           X86-64 (Native)
Role:                Default
Parent Process:      launchd [1]
Coalition:           org.chenhb23.lanzou [1566]

Date/Time:           2021-12-29 21:30:18.0516 -0500
Launch Time:         2021-12-29 21:30:18.0334 -0500
OS Version:          macOS 12.1 (21C52)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: CODESIGNING 1 

Triggered by Thread:  0

Thread 0 Crashed:
0                                 	       0x109de6ac0 _dyld_start + 0
1                                	       0x105c84000 ???

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ff7ba27bbd8
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000109de6ac0  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000 
Trap Number:     0

Binary Images:
       0x109de2000 -        0x109e4dfff  (*) <cef5a27a-d50b-3020-af03-1734b19bc8c5> ???
       0x105c84000 -        0x105cabfff  (*) <5cf444e6-280a-33a3-87ff-b56a6b4ec25c> 

Error Formulating Crash Report:
dyld_process_snapshot_get_shared_cache failed

EOF

-----------
Full Report
-----------

{"app_name":"蓝奏云盘","timestamp":"2021-12-29 21:30:18.00 -0500","app_version":"1.0.8","slice_uuid":"5cf444e6-280a-33a3-87ff-b56a6b4ec25c","build_version":"1.0.8","platform":0,"bundleID":"org.chenhb23.lanzou","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.1 (21C52)","incident_id":"E4483780-0B2A-4B1B-8628-ACDF7FAD0EB3","name":"蓝奏云盘"}
{
  "uptime" : 1800,
  "procLaunch" : "2021-12-29 21:30:18.0334 -0500",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro15,4",
  "procStartAbsTime" : 1810123590386,
  "coalitionID" : 1566,
  "osVersion" : {
    "train" : "macOS 12.1",
    "build" : "21C52",
    "releaseType" : "User"
  },
  "captureTime" : "2021-12-29 21:30:18.0516 -0500",
  "incident" : "E4483780-0B2A-4B1B-8628-ACDF7FAD0EB3",
  "bug_type" : "309",
  "pid" : 1624,
  "procExitAbsTime" : 1810141156840,
  "cpuType" : "X86-64",
  "procName" : "蓝奏云盘",
  "procPath" : "\/Applications\/蓝奏云盘.app\/Contents\/MacOS\/蓝奏云盘",
  "bundleInfo" : {"CFBundleShortVersionString":"1.0.8","CFBundleVersion":"1.0.8","CFBundleIdentifier":"org.chenhb23.lanzou"},
  "storeInfo" : {"deviceIdentifierForVendor":"16631C5B-574D-5EFD-8FA8-D1F6DE3293B5","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.chenhb23.lanzou",
  "crashReporterKey" : "FA00274D-BC6B-EB3F-A21B-6EA520AC3294",
  "bridgeVersion" : {"build":"19P647","train":"6.1"},
  "sip" : "disabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL (Code Signature Invalid)"},
  "termination" : {"namespace":"CODESIGNING","flags":66,"code":1},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":34096,"threadState":{"r13":{"value":0},"rax":{"value":0},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":0},"rsi":{"value":0},"r8":{"value":0},"cr2":{"value":0},"rdx":{"value":0},"r10":{"value":0},"r9":{"value":0},"r15":{"value":0},"rbx":{"value":0},"trap":{"value":0},"err":{"value":0},"r11":{"value":0},"rip":{"value":4460538560,"matchesCrashFrame":1},"rbp":{"value":0},"rsp":{"value":140701956815832},"r12":{"value":0},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":0}},"frames":[{"imageOffset":19136,"symbol":"_dyld_start","symbolLocation":0,"imageIndex":0},{"imageOffset":0,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4460519424,
    "size" : 442368,
    "uuid" : "cef5a27a-d50b-3020-af03-1734b19bc8c5",
    "name" : ""
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4391976960,
    "size" : 163840,
    "uuid" : "5cf444e6-280a-33a3-87ff-b56a6b4ec25c",
    "path" : "\u0004",
    "name" : "\u0004"
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=816K resident=0K(0%) swapped_out_or_unallocated=816K(100%)\nWritable regions: Total=8196K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8196K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                          8K        2 \n__DATA                              32K        3 \n__DATA_CONST                        80K        1 \n__LINKEDIT                         240K        4 \n__TEXT                             592K        2 \n===========                     =======  ======= \nTOTAL                             64.9M       14 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "6193d03f2171a2330e561dfc"
      },
      "deploymentId" : 240000290
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000090
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000196
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "61c11dcd2cb6041dc630dc63"
      },
      "deploymentId" : 240000357
    }
  ],
  "experiments" : [

  ]
},
  "reportNotes" : [
  "dyld_process_snapshot_get_shared_cache failed"
]
}

Model: MacBookPro15,4, BootROM 1715.60.5.0.0 (iBridge: 19.16.10647.0.0,0), 4 processors, Quad-Core Intel Core i5, 1.4 GHz, 16 GB, SMC 
Graphics: Intel Iris Plus Graphics 645, Intel Iris Plus Graphics 645, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, LPDDR3, 2133 MHz, SK Hynix, H9CCNNNCLGALAR-NVD
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, LPDDR3, 2133 MHz, SK Hynix, H9CCNNNCLGALAR-NVD
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x870), wl0: Jul 16 2021 18:25:13 version 16.20.328.0.3.6.105 FWID 01-30be2b3a
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: T2Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 63.5

完全不懂代码，求大佬帮忙

**Comment by chenhb23** [comment]
已支持 macOS Monterey 系统（Intel平台），可重新下载 [1.0.8](https://github.com/chenhb23/lanzouyun-disk/releases/download/v1.0.8/lanzouyun-1.0.8.dmg) 版本后再试

**Comment by Olivia-K99** [comment]
emmm 这回可以打开了，但下载后还是显示为一个html的文件，跟之前一样…还是请大佬再看看TAT
