### ISSUE TITLE
jser大大，我下载了3.4.3压缩包但是打开后还是显示的是3.4.2的怎么办鸭

### ISSUE THREAD

**Issue by oinjser** [chenhb23/lanzouyun-disk#113]
![20230409000638](https://user-images.githubusercontent.com/126697479/230731416-701aebbb-8d74-4ac7-a0be-def1335e2ead.png)

**Comment by oinlikejser** [comment]
![20230409002233](https://user-images.githubusercontent.com/126697479/230732070-05ade880-1873-4aba-8cd5-734e1d95cac4.png)
![20230409002253](https://user-images.githubusercontent.com/126697479/230732079-5b79c160-0d3f-4526-abc4-83ca1c7f6b94.png)
