### ISSUE TITLE
建议增加刷新按钮

### ISSUE THREAD

**Issue by wonchong** [chenhb23/lanzouyun-disk#118]
建议在这个位置增加个刷新按钮，更新了，远程还没显示更新，这时候就得点上一级文件夹再点击回来进行刷新，我个人认为，有个刷新按钮更加方便。
![image](https://github.com/chenhb23/lanzouyun-disk/assets/82252714/966e3f2d-e3f4-459d-bf6b-a115fb96eca4)

**Comment by chenhb23** [comment]
点一下当前目录即可刷新

<img width="1272" alt="image" src="https://github.com/chenhb23/lanzouyun-disk/assets/74194963/9e74fb4d-9eef-49f8-a55c-c70a51d0a75e">
