### ISSUE TITLE
无法下载单一文件，也无法使用批量下载功能下载一个文件夹下的多个文件。

### ISSUE THREAD

**Issue by petrichorlulu** [chenhb23/lanzouyun-disk#126]
使用解析功能解析完蓝奏链接后，点击下载，没有任何进度条，后面的按钮也是暂停的三角。重新点击按钮试图下载也会立刻变回暂停状态。没有办法下载任何链接，不论是单一文件还是文件夹。电脑内存是够的，不知道为什么没有办法下载文件。

**Comment by chenhb23** [comment]
官方更新了规则，影响到了下载功能，发了新版本，可以试试

**Comment by petrichorlulu** [comment]
下了新版本，可以批量下载文件了，谢谢大大！
