### ISSUE TITLE
批量下载功能无法使用

### ISSUE THREAD

**Issue by oinlikejser** [chenhb23/lanzouyun-disk#128]
jser大大，程序的批量下载功能无法使用，点击“下载”按钮后只显示项目，但是每一个都没有speed，如图
[![20230820013012.png](https://i.postimg.cc/90DjScRh/20230820013012.png)](https://postimg.cc/Zvzgvtx7)

**Comment by chenhb23** [comment]
更新了参数匹配规则，下载功能可以用了
