### ISSUE TITLE
更新到3.4.5. Mac, 任务创建后蓝奏还是无法下载，一直暂停

### ISSUE THREAD

**Issue by mellowmellow88** [chenhb23/lanzouyun-disk#130]
<img width="718" alt="Screenshot 2023-08-22 at 14 34 35" src="https://github.com/chenhb23/lanzouyun-disk/assets/142873851/8bacc0fd-2e85-4521-9cdb-eb6dd7219e29">
更新到3.4.5首先arm这个装不了因为说文件损坏，装了x64的mac，装好后用了批量下载，创建了文件但是就自动暂停，再按也会自动暂停，下载不下来，然后用解析去下载文件也是如图这样，创建，就自动暂停不下载，麻烦大大修复，已经连续四天这样了，以为下载最新版会好，但是没想到还是没办法下载。辛苦你！

**Comment by chenhb23** [comment]
官方又更新脚本了，app重新下

**Comment by mellowmellow88** [comment]
> 官方又更新脚本了，app重新下
谢谢大大！可以用了，但还是好奇为什么arm4.5和4.6都装不起来都说文件损坏，以往的却都可以装？我现在装了mac的x64
