### ISSUE TITLE
无法使用下载功能下载文件 报错：Cookie not in this host's domain. Cookie: lanzouk.com Request: developer-oss.lanzouc.com

### ISSUE THREAD

**Issue by petrichorlulu** [chenhb23/lanzouyun-disk#135]
请大大修复下载功能，无论是解析后下载文件；还是从正在下载里新建任务都报错。
显示：Cookie not in this host's domain. Cookie: lanzouk.com Request: developer-oss.lanzouc.com；无法下载文件。

![无法下载](https://github.com/chenhb23/lanzouyun-disk/assets/142663114/8d12dd62-3ecc-4597-a60d-550d2df344bf)

**Comment by YRVE123** [comment]
我也是遇到了这个问题
