### ISSUE TITLE
下载时报错！cookie not in this host"s domain, cookie：lanzouc.com Request:developer-oss.lanzouk.com 

### ISSUE THREAD

**Issue by mellowmellow88** [chenhb23/lanzouyun-disk#146]
下载时报错！下载时报错！cookie not in this host"s domain, cookie：lanzouc.com Request:developer-oss.lanzouk.com 
昨天还好的请帮帮忙修复了！
<img width="631" alt="Screenshot 2024-01-05 at 09 09 17" src="https://github.com/chenhb23/lanzouyun-disk/assets/142873851/5d7fa643-09e1-4f30-88c5-14290209690f">

**Comment by huanglong6828** [comment]
+1

**Comment by huanglong6828** [comment]
原因排查 文件下载地址域名：https://developer-oss.lanrar.com:81  cookie初始化： domain: 'pc.woozooo.com' 导致got.extend({cookieJar: shareCookieJar}）校验失败。

**Comment by Kosuke88** [comment]
> 原因排查 文件下载地址域名：https://developer-oss.lanrar.com:81 cookie初始化： domain: 'pc.woozooo.com' 导致got.extend({cookieJar: shareCookieJar}）校验失败。

想问下这个要怎么解决啊

**Comment by mellowmellow88** [comment]
> 原因排查 文件下载地址域名：https://developer-oss.lanrar.com:81 cookie初始化： domain: 'pc.woozooo.com' 导致got.extend({cookieJar: shareCookieJar}）校验失败。

要怎么解决呢？

**Comment by huanglong6828** [comment]
我能解决的办法只有下载源码删除校验代码 重新打包。我已经打包出来在使用了，目前没问题。需要的话提供邮箱 明天给你们。

**Comment by mellowmellow88** [comment]
> 我能解决的办法只有下载源码删除校验代码 重新打包。我已经打包出来在使用了，目前没问题。需要的话提供邮箱 明天给你们。

我可以要苹果mac的吗？wonnow37@gmail.com 谢谢

**Comment by Kosuke88** [comment]
> 我能解决的办法只有下载源码删除校验代码 重新打包。我已经打包出来在使用了，目前没问题。需要的话提供邮箱 明天给你们。
jenniewhite0012@outlook.com麻烦了

**Comment by cheneylee5752** [comment]
> 我能解决的办法只有下载源码删除校验代码 重新打包。我已经打包出来在使用了，目前没问题。需要的话提供邮箱 明天给你们。

可以将新打包的文件发一份蓝奏吗感谢

**Comment by petrichorlulu** [comment]
> > 我能解决的办法只有下载源码删除校验代码 重新打包。我已经打包出来在使用了，目前没问题。需要的话提供邮箱 明天给你们。
> 
> 可以将新打包的文件发一份蓝奏吗感谢

需要删除验证码的版本 邮箱：2676944390@qq.com 万分感谢！
