### ISSUE TITLE
下载不了显示connect etimedout 221.228.32.13.661

### ISSUE THREAD

**Issue by Ayu1113** [chenhb23/lanzouyun-disk#157]

**Comment by chenhb23** [comment]
提供个测试文件的链接

**Comment by lydiashannon** [comment]
遇到了同样的问题

**Comment by Ayu1113** [comment]
> 有可能是蓝奏云服务器抽了，如果还不能下载，提供个测试文件的链接我调试一下

https://wwd.lanzn.com/iyXER20rm3ch

**Comment by chenhb23** [comment]
<img width="1246" alt="image" src="https://github.com/chenhb23/lanzouyun-disk/assets/74194963/674331b4-2ef7-40c5-96e8-450e72dbf952">

正常下载

**Comment by Ayu1113** [comment]
> <img alt="image" width="1246" src="https://private-user-images.githubusercontent.com/74194963/336369875-674331b4-2ef7-40c5-96e8-450e72dbf952.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTExNDcsIm5iZiI6MTcxNzQ5MDg0NywicGF0aCI6Ii83NDE5NDk2My8zMzYzNjk4NzUtNjc0MzMxYjQtMmVmNy00MGM1LTk2ZTgtNDUwZTcyZGJmOTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA4NDcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZDlmMjZiMGJmZGM4MTNjMTRmMGFjZjFlMTkzODNkNWEyNWYwOTRhMmNmY2Q3NjMyYzNlNmM1ZWI1YWIxOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zWlymx-odPysJCk_WwOjJUATT2aFOzkCOF45HRIcLdo">
> 正常下载

![屏幕截图(120)](https://github.com/chenhb23/lanzouyun-disk/assets/171451790/651ed528-53d0-48d3-b7fe-286e726abb0f)

**Comment by Ayu1113** [comment]
> <img alt="image" width="1246" src="https://private-user-images.githubusercontent.com/74194963/336369875-674331b4-2ef7-40c5-96e8-450e72dbf952.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTExNDcsIm5iZiI6MTcxNzQ5MDg0NywicGF0aCI6Ii83NDE5NDk2My8zMzYzNjk4NzUtNjc0MzMxYjQtMmVmNy00MGM1LTk2ZTgtNDUwZTcyZGJmOTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA4NDcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZDlmMjZiMGJmZGM4MTNjMTRmMGFjZjFlMTkzODNkNWEyNWYwOTRhMmNmY2Q3NjMyYzNlNmM1ZWI1YWIxOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zWlymx-odPysJCk_WwOjJUATT2aFOzkCOF45HRIcLdo">
> 正常下载

![屏幕截图(121)](https://github.com/chenhb23/lanzouyun-disk/assets/171451790/d92f40b3-c0c1-46bd-91a2-e78d6d83e784)
我还是一样提示这个

**Comment by Ayu1113** [comment]
> <img alt="image" width="1246" src="https://private-user-images.githubusercontent.com/74194963/336369875-674331b4-2ef7-40c5-96e8-450e72dbf952.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NDMzMDEsIm5iZiI6MTcxNzU0MzAwMSwicGF0aCI6Ii83NDE5NDk2My8zMzYzNjk4NzUtNjc0MzMxYjQtMmVmNy00MGM1LTk2ZTgtNDUwZTcyZGJmOTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDIzMTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4NjBhNGE0OTQ5NmFlYmI3NDJhYjMxNzAyODVhYzkyMjk4YTVkZTRiMDUyYmE4ZGNhMzNhMjU5MzE1YTNkZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ryFwMGv1zcvA5Z6vV4YSf9U-r1T9ShcqNr9Fs723hCo">
> 正常下载

评论里面也有其他人遇到同样的问题

**Comment by oinjser** [comment]
> <img alt="image" width="1246" src="https://private-user-images.githubusercontent.com/74194963/336369875-674331b4-2ef7-40c5-96e8-450e72dbf952.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NDY2NDksIm5iZiI6MTcxNzU0NjM0OSwicGF0aCI6Ii83NDE5NDk2My8zMzYzNjk4NzUtNjc0MzMxYjQtMmVmNy00MGM1LTk2ZTgtNDUwZTcyZGJmOTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDAwMTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MGQzN2ExZTIyYzNiZjcxMzU4ZDk1ZDliNDFkM2ZjOWU0OGNhNmQ4ZTRjYTAxNDY4ZmE2MzUzN2I1NzIyOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3hGhfsmvKWWlSu4B69O-yP-cCn6H1xQy7uIFjEOOvgU">
> 正常下载
大佬，好像只有你能正常下载，已经好几天了

**Comment by chenhb23** [comment]
试试看最新的 v3.4.9 版本还有 connect 的问题吗

**Comment by oinjser** [comment]
好的！我等会儿试试
---- 回复的原邮件 ----
***@***.***>发送日期2024年06月05日 16:01 ***@***.***> ***@***.***>,
***@***.***>主题Re: [chenhb23/lanzouyun-disk] 下载不了显示connect etimedout 221.228.32.13.661 (Issue #157)
试试看最新的 v3.4.9 版本还有 connect 的问题吗

**Comment by oinjser** [comment]
可以下载了，谢谢(🙏•͈ᴗ•͈)
---- 回复的原邮件 ----
***@***.***>发送日期2024年06月05日 16:01 ***@***.***> ***@***.***>,
***@***.***>主题Re: [chenhb23/lanzouyun-disk] 下载不了显示connect etimedout 221.228.32.13.661 (Issue #157)
试试看最新的 v3.4.9 版本还有 connect 的问题吗

**Comment by oinjser** [comment]
想知道是什么问题(´･ω･`)?
---- 回复的原邮件 ----
***@***.***>发送日期2024年06月05日 16:01 ***@***.***> ***@***.***>,
***@***.***>主题Re: [chenhb23/lanzouyun-disk] 下载不了显示connect etimedout 221.228.32.13.661 (Issue #157)
试试看最新的 v3.4.9 版本还有 connect 的问题吗

**Comment by chenhb23** [comment]
接口参数变了，蓝奏云加了个 killdns 的变量，如果不处理的话就可能有问题

**Comment by Ayu1113** [comment]
> 试试看最新的 v3.4.9 版本还有 connect 的问题吗

谢谢，可以下载了
