### ISSUE TITLE
无法下载文件了

### ISSUE THREAD

**Issue by oinjser** [chenhb23/lanzouyun-disk#158]
![20240603000207](https://github.com/chenhb23/lanzouyun-disk/assets/126697479/52c0a095-fa4b-48f4-b3e9-bbc255a7a7ef)
首先感谢您的程序，这十分好用且方便，功能也很强大，但是最近好像出现了无法下载的问题，提示timeout好多次，卸载重装也没有解决问题，该怎么办

**Comment by oinjser** [comment]
![20240603010132](https://github.com/chenhb23/lanzouyun-disk/assets/126697479/286bc258-f53c-4632-b8c4-974357af860d)

**Comment by chenhb23** [comment]
首先确保文件在蓝奏云网页端能正常显示和下载，如果链接有问题软件也是无能为力的；

如果是网页端正常，软件不能下载的，可以给个文件的链接，我调试一下

**Comment by oinjser** [comment]
这个链接：https://wwo.lanzov.com/b00g2c102f
---- 回复的原邮件 ----
***@***.***>发送日期2024年06月03日 10:34 ***@***.***> ***@***.***>,
***@***.***>主题Re: [chenhb23/lanzouyun-disk] 无法下载文件了 (Issue #158)
首先确保文件在蓝奏云网页端能正常显示和下载，如果链接有问题软件也是无能为力的；
如果是网页端正常，软件不能下载的，可以给个文件的链接，我调试一下

**Comment by chenhb23** [comment]
<img width="1279" alt="image" src="https://github.com/chenhb23/lanzouyun-disk/assets/74194963/1dd38054-af73-4199-a644-6ef4a26263d8">

都能下载的，是不是蓝奏云服务器抽了

**Comment by oinjser** [comment]
那我再试试！(ง•̀_•́)ง谢谢大大❤️
---- 回复的原邮件 ----
***@***.***>发送日期2024年06月03日 13:43 ***@***.***> ***@***.***>,
***@***.***>主题Re: [chenhb23/lanzouyun-disk] 无法下载文件了 (Issue #158)
image.png (view on web) 都能下载的，是不是蓝奏云服务器抽了

**Comment by oinjser** [comment]
> <img alt="image" width="1279" src="https://private-user-images.githubusercontent.com/74194963/335950242-1dd38054-af73-4199-a644-6ef4a26263d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDgwMTEsIm5iZiI6MTcxNzQwNzcxMSwicGF0aCI6Ii83NDE5NDk2My8zMzU5NTAyNDItMWRkMzgwNTQtYWY3My00MTk5LWE2NDQtNmVmNGEyNjI2M2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA5NDE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNjQ3ZTBiNWRlYmRiNThmNzE3ODUyOWQ4NjVmZWIwYWQ5OGQ0OTllNjMyZDNjM2Y3MTk1MjcyNzE4MDQ3Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.07jv8j5tZgi9mJx2FmKYdeccYKHBiuOtpM4mZBOyY_Q">
> 都能下载的，是不是蓝奏云服务器抽了

**Comment by oinjser** [comment]
大大，不是说如果是会员的话可以上传 300M文件吗？我开通了 25/月的但是还是限制在 150M｡°(°¯᷄◠¯᷅°)°｡
---- 回复的原邮件 ----
***@***.***>发送日期2024年06月03日 13:43 ***@***.***> ***@***.***>,
***@***.***>主题Re: [chenhb23/lanzouyun-disk] 无法下载文件了 (Issue #158)
image.png (view on web) 都能下载的，是不是蓝奏云服务器抽了

**Comment by chenhb23** [comment]
<img width="458" alt="image" src="https://github.com/chenhb23/lanzouyun-disk/assets/74194963/3e206620-ac86-4ec8-b015-97ae8b5662b8">

个人中心页面显示多少就会限制多少
