### ISSUE TITLE
无法下载文件，显示：unexpected identifier。

### ISSUE THREAD

**Issue by petrichorlulu** [chenhb23/lanzouyun-disk#159]
请大大修复下载功能，从正在下载里新建批量任务，以及从解析url里都无法下载文件；显示 unexpected identifier。
![Snipaste_2024-06-14_10-17-06](https://github.com/chenhb23/lanzouyun-disk/assets/142663114/c2883e94-5fb7-4b38-9e18-55e617891e31)

**Comment by Amanda342010** [comment]
的确是这样的，我也是如此
![微信截图_20240614134211](https://github.com/chenhb23/lanzouyun-disk/assets/172741873/c3dec5eb-0b22-405a-a634-1b91c0431d35)

**Comment by huanglong6828** [comment]
解析URL页面进去，排查到prettier.format函数报错
![image](https://github.com/chenhb23/lanzouyun-disk/assets/19216952/1f778f98-0468-47ec-a5b7-0b2a3512aef6)

**Comment by chenhb23** [comment]
> 解析URL页面进去，排查到prettier.format函数报错 ![image](https://private-user-images.githubusercontent.com/19216952/339725742-1f778f98-0468-47ec-a5b7-0b2a3512aef6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzYxNDIsIm5iZiI6MTcxODM3NTg0MiwicGF0aCI6Ii8xOTIxNjk1Mi8zMzk3MjU3NDItMWY3NzhmOTgtMDQ2OC00N2VjLWE1YjctMGIyYTM1MTJhZWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE0MzcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlY2Y0ZDlmYWNkZGZmNTY4OWUyNTliNTYyYmIyOWNlZWRkYmQyZDI0N2VjYWVmNDNlNzJiOWIzZTQ4MmFhNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9mpu71mraRokCJN9EG_IREl62gT-ApkTxCvTO4sWdJw)

多谢提供的报错信息，新版本已修复

**Comment by petrichorlulu** [comment]
> > 解析URL页面进去，排查到prettier.format函数报错 ![image](https://private-user-images.githubusercontent.com/19216952/339725742-1f778f98-0468-47ec-a5b7-0b2a3512aef6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzYxNDIsIm5iZiI6MTcxODM3NTg0MiwicGF0aCI6Ii8xOTIxNjk1Mi8zMzk3MjU3NDItMWY3NzhmOTgtMDQ2OC00N2VjLWE1YjctMGIyYTM1MTJhZWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE0MzcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlY2Y0ZDlmYWNkZGZmNTY4OWUyNTliNTYyYmIyOWNlZWRkYmQyZDI0N2VjYWVmNDNlNzJiOWIzZTQ4MmFhNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9mpu71mraRokCJN9EG_IREl62gT-ApkTxCvTO4sWdJw)
> 
> 多谢提供的报错信息，新版本已修复

可以下载了，谢谢大大！
