### ISSUE TITLE
救命我又来了

### ISSUE THREAD

**Issue by Olivia-K99** [chenhb23/lanzouyun-disk#16]
球球大佬能不能弄个支持苹果m1芯片的 orz 实在是用不了 有偿也可以QAQ

**Comment by chenhb23** [comment]
> 球球大佬能不能弄个支持苹果m1芯片的 orz 实在是用不了 有偿也可以QAQ

m1 这个可以有。如果你觉得软件帮到了你，请我喝杯奶茶也是可以的 [旺柴]

**Comment by chenhb23** [comment]
来晚了！arm版已经发上了。如果有问题可以提出

**Comment by Olivia-K99** [comment]
> 来晚了！arm版已经发上了。如果有问题可以提出

讨厌一些网络烂梗但是此刻没有什么其他语言可以表达我的心情 so
大佬你是我的神！！

哈哈哈哈哈哈哈
请让我请你喝奶茶 祝大佬身体健康！
