### ISSUE TITLE
无法解析链接了

### ISSUE THREAD

**Issue by oinjser** [chenhb23/lanzouyun-disk#160]
网页上直接点蓝奏云链接可以打开，但是放到软件里就无法解析了
![20240614192203](https://github.com/chenhb23/lanzouyun-disk/assets/126697479/009e8ebc-c4a5-4225-ac9a-ebc343994e82)
测试链接：https://www.lanzouv.com/b0r998zyd
密码：6666

**Comment by chenhb23** [comment]
感谢提供的链接，新版本问题已修复
