### ISSUE TITLE
无法上传文件，请大大修复上传功能。

### ISSUE THREAD

**Issue by petrichorlulu** [chenhb23/lanzouyun-disk#163]
上传文件时有进度条，但是完成时没有文件出现在文件夹当中。请大大修复一下，谢谢大大！
![上传问题](https://github.com/chenhb23/lanzouyun-disk/assets/142663114/17caa00a-31f5-424a-86fd-af759e777b52)
![上传问题2](https://github.com/chenhb23/lanzouyun-disk/assets/142663114/9518c254-a087-4965-8693-d899872c2fce)

**Comment by chenhb23** [comment]
更新到 3.5.0 版本试试看

**Comment by petrichorlulu** [comment]
> 更新到 3.5.0 版本试试看

更新到3.5.1了，还是上传不了啊，大大。有进度条，就是文件夹没文件出现。

**Comment by chenhb23** [comment]
3.5.2 可以上传了

**Comment by petrichorlulu** [comment]
> 3.5.2 可以上传了

上传成功了，谢谢大大！
