### ISSUE TITLE
无法上传文件了

### ISSUE THREAD

**Issue by oinjser** [chenhb23/lanzouyun-disk#164]

**Comment by chenhb23** [comment]
久等了，更新到 3.5.0 版本试试看

**Comment by huangshixian2023** [comment]
3.5.0 咋登入后就到官网了

**Comment by chenhb23** [comment]
x64平台打出来的包有问题，换成arm64平台进行打包了。重新下 3.5.1 的包

**Comment by huangshixian2023** [comment]
谢啦

**Comment by oinjser** [comment]
> x64平台打出来的包有问题，换成arm64平台进行打包了。하里하 3.5.1 的包



> 谢啦

辛苦了🥳

**Comment by oinjser** [comment]
还是不行，传不上文件(ಥ_ಥ)
---- 回复的原邮件 ----
发件人Huang Shi ***@***.***>发送日期2024年07月16日 10:51 ***@***.***> ***@***.***>,
***@***.***>主题Re: [chenhb23/lanzouyun-disk] 无法上传文件了 (Issue #164)
谢啦
