### ISSUE TITLE
建议增加几个功能 2022.3.24

### ISSUE THREAD

**Issue by zuixiangsi** [chenhb23/lanzouyun-disk#18]
希望大佬能增加几个更佳便捷的功能：

1、增加文件多选和全选下载功能功能，这样同时下载多个文件更佳方便。
2、增加排序功能，现在上传文件的排序是按照上传完成先后顺序排序的，而很多教程类资源是有很多课程，现在上传后顺序会很乱，如果能进行排序就很奈斯了。

**Comment by Dyxtl** [comment]
希望大佬可以增加在线编辑文件名的功能

**Comment by chenhb23** [comment]
> 希望大佬能增加几个更佳便捷的功能：
> 1、增加文件多选和全选下载功能功能，这样同时下载多个文件更佳方便。  
> 2、增加排序功能，现在上传文件的排序是按照上传完成先后顺序排序的，而很多教程类资源是有很多课程，现在上传后顺序会很乱，如果能进行排序就很奈斯了。

> 希望大佬可以增加在线编辑文件名的功能

来晚了，功能已加！
