### ISSUE TITLE
1.0.9版本每次上传到最后几M的时候就停掉了

### ISSUE THREAD

**Issue by DeathInTheAir** [chenhb23/lanzouyun-disk#19]
重启上传又会周而复始

**Comment by mandarine250** [comment]
附议！也是每次上传到最后一丢丢的时候就会断掉，然后再上传再循环

不过倒是可以先行自己分卷压缩 再全部上传 这样下载下来效果也是一样的

**Comment by Dyxtl** [comment]
附议！想上传一个视频也是无限循环上传

**Comment by chenhb23** [comment]
暂时先别用软件上传超过100m的文件。

**Comment by lightoalawliet** [comment]
我也是！都是在上传超过100m的文件时，在最后几十m的时候，就自动暂停，然后减少上传的进度，再上传，就这样自动循环...

**Comment by chenhb23** [comment]
试试 1.0.10 版本吧

**Comment by Jormangund1** [comment]
> 试试1.0.10版本吧

1.0.10也是，还提示不要使用第三方工具

**Comment by chenhb23** [comment]
已修复了
