### ISSUE TITLE
新图标

### ISSUE THREAD

**Issue by zx1621** [chenhb23/lanzouyun-disk#2]
我从 http://www-ori.nipic.com/show/31815880.html 这个网站找到的图，然后以此制作了新的icon，新的icon在这里：
https://cdn.jsdelivr.net/gh/zx1621/oss@master/uPic/lanzou.icns

**Comment by chenhb23** [comment]
谢谢你提供的 icon，但是该图标版权属于蓝奏官方。如果可以的话，你可以设计一个图标，作为这款开源软件的 icon。


| |
chenhongbo_1994
|
|
chenhongbo_1994@163.com
|
签名由网易邮箱大师定制


在2021年01月9日 19:57，Zhang Xu<notifications@github.com> 写道：

我从 http://www-ori.nipic.com/show/31815880.html 这个网站找到的图，然后以此制作了新的icon，新的icon在这里：
https://cdn.jsdelivr.net/gh/zx1621/oss@master/uPic/lanzou.icns
