### ISSUE TITLE
大文件合成下载完成后无法直接打开

### ISSUE THREAD

**Issue by muzz001** [chenhb23/lanzouyun-disk#20]
提示文件被其他软件占用，需要先关闭网盘，再打开文件才可以，希望可以进一步修复！
感谢作者的贡献！

**Comment by chenhb23** [comment]
来晚了！为了支持苹果 arm 芯片，升级了 electron 版本，同时新增了一下功能。这个问题已顺带解决了，可试试 v2 版本
