### ISSUE TITLE
上传不上去大文件，提示：错误7072

### ISSUE THREAD

**Issue by dongri1415760211** [chenhb23/lanzouyun-disk#21]
上传不上去。文件夹空的，提示：错误7072
![750a37b8b64debb7002020d15d4f769a_%2Fapp%2Fa%2F100520146%2F65e1de31619986ed013a03e2decd0153](https://user-images.githubusercontent.com/47824205/162340643-03856b59-47f6-4eaf-9d1d-d93d21c7ff68.png)
![4dbf6958da4a87d2c5887d08386b8a26_%2Fapp%2Fa%2F100520146%2Feb6da25f100b196d858539fe3ed29f23](https://user-images.githubusercontent.com/47824205/162340683-c2112410-c461-4201-afd4-5c6cfae56e91.png)

**Comment by EternalRiz** [comment]
我也是这样...上传上去后，文件变成文件夹了还。请问你解决了吗

**Comment by chenhb23** [comment]
> 我也是这样...上传上去后，文件变成文件夹了还。请问你解决了吗

上传大文件前，会新建同名文件夹，而不是文件变成了文件夹。如果此时上传失败，是不会删除新建的文件夹的

**Comment by dongri1415760211** [comment]
![image](https://user-images.githubusercontent.com/47824205/163725614-fe827fd7-ac0a-434f-9880-43f2ef1d5bbd.png)
新版一样传不了大文件啊？只有第一个文件可以成功上传。

**Comment by dongri1415760211** [comment]
> 我也是这样上传上去后，文件文件夹还...。

没解决，继续等待作者更新版本修复问题中……

**Comment by dongri1415760211** [comment]
> 我也是这样...上传上去后，文件变成文件夹了还。请问塔解决了吗

没解决，新版只能成功上传第一个分割文件，传不上去第二个分割文件。

**Comment by chenhb23** [comment]
可以试试 v2.1.1 新版本
