### ISSUE TITLE
上传的文件变成文件夹

### ISSUE THREAD

**Issue by EternalRiz** [chenhb23/lanzouyun-disk#23]
明明是7z压缩包格式，上传上去后就变成了文件夹了。尝试了其他格式，依旧如此，只有某些文件不会被改。不知道为何

**Comment by chenhb23** [comment]
文件过大会把文件分割成小文件，上传在网盘新建的同名目录下

**Comment by EternalRiz** [comment]
开了会员了，上限是300M了，难不成是超过默认100M就分割？

**Comment by EternalRiz** [comment]
> 文件过大会把文件分割成小文件，上传在网盘新建的同名目录下

开了会员了，上限是300M了，难不成是超过默认100M就分割？如果有不限制就好了

**Comment by EternalRiz** [comment]
> 文件过大会把文件分割成小文件，上传在网盘新建的同名目录下

我是拿蓝奏云做为主要网盘分享，有时候会有超过上限的，就使用的是分卷压缩。单个包单个包这样，分割成小文件。。就蛋疼了~

**Comment by chenhb23** [comment]
可以考虑开发一下。进来先查询一把用户信息，如果是会员，把上限提升至 300m

**Comment by EternalRiz** [comment]
> 可以考虑开发一下。进来先查询一把用户信息，如果是会员，把上限提升至 300m

感谢大大！

**Comment by chenhb23** [comment]
会员账号的上限已提升到300m

**Comment by EternalRiz** [comment]
> 会员账号的上限已提升到300m

测试，没有问题！感谢大佬！

**Comment by lpx2223** [comment]
你好，这个功能是，只要开了比如150M一类的蓝奏会员，用这个就会自动提升到300M吗？我刚买的150M会员，登录账号后还是没办法上传超过150M的东西。
