### ISSUE TITLE
请问下，在2.0.0版本中上传大文件的时候，会在上传到95mb或者190mb的时候提示错误

### ISSUE THREAD

**Issue by shaochen206** [chenhb23/lanzouyun-disk#24]
错误提示
RequestError：无法识别文件内容，请联系客服处理

**Comment by chenhb23** [comment]
文件上传后，官方可能会对常规文件进行扫描，分块文件是不能读取的，所以返回错误。

试试将文件放到文件夹里，然后将文件夹压缩后上传

**Comment by shaochen206** [comment]
试过了把文件放在文件夹中，在把文件夹压缩上传压缩包，也还是一样的报错

**Comment by Vicey2004** [comment]
我也遇到同样的问题，到95M或190M就无法识别了，压缩后也一样

**Comment by gzmars** [comment]
我也一样，上传两个200M的文件，一个停在190M，一个停在95M。

**Comment by mandarine250** [comment]
一样 暂时没有例外的成功上传

**Comment by 64-SpaceL** [comment]
依旧行不通，无论是中文名称修改还是文件夹放置都会卡上传！！！

**Comment by chenhb23** [comment]
可以试试 v2.1.1 新版本
