### ISSUE TITLE
在mac11.0无法使用

### ISSUE THREAD

**Issue by Olivia-K99** [chenhb23/lanzouyun-disk#3]
解析完链接之后点击全部下载上方跳出无数个“done”，在正在下载页面当中发现无数次重复下载-停止过程，尝试重启电脑和重装软件无法解决，请看看

**Comment by chenhb23** [comment]
官方下载接口有修改，增加了sign签名，导致解析失败，现已修复！

**Comment by Olivia-K99** [comment]
不好意思，下载了之后仍然会有同样的问题……

**Comment by chenhb23** [comment]
是否是 1.0.2 版本，不要覆盖安装，尝试一下卸载后再安装
[![ymoUDs.png](https://s3.ax1x.com/2021/02/02/ymoUDs.png)](https://imgchr.com/i/ymoUDs)

**Comment by Olivia-K99** [comment]
get it 现在搞定了，谢谢。
