### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Monokuma689** [chenhb23/lanzouyun-disk#30]
下次更新建议添加上叉页面的按钮，可以把软件图标换一下，图标我已经做好了一个
[图标.zip](https://github.com/chenhb23/lanzouyun-disk/files/8547372/default.zip)

**Comment by tianxuanzhizi** [comment]
同，没关闭图标难受。。。

**Comment by chenhb23** [comment]
早就加上了，请确保 app 是最新版本

**Comment by tianxuanzhizi** [comment]
> 早就加上了，请确保 app 是最新版本

嗯嗯，发现了
![19FED4F6](https://user-images.githubusercontent.com/22144485/166099114-63d9a654-3c6a-431a-9f20-fe13fe883c12.png)
