### ISSUE TITLE
更新V2.1后界面上方没有了菜单栏以及缩小放大关闭的按钮

### ISSUE THREAD

**Issue by muzz001** [chenhb23/lanzouyun-disk#32]
![1650736435(1)](https://user-images.githubusercontent.com/80476842/164933960-d3fb04ec-2426-4a9b-86f7-d7e3d7887d36.jpg)

**Comment by chenhb23** [comment]
v2.1.1 版本已经加上了

**Comment by chenhb23** [comment]
现在都3+版本了，可以到 release 中下载
