### ISSUE TITLE
文件超过198M就无法上传，显示无法识别文件内容

### ISSUE THREAD

**Issue by Monokuma689** [chenhb23/lanzouyun-disk#34]

**Comment by chenhb23** [comment]
可以试试 v2.1.1 新版本

**Comment by Monokuma689** [comment]
大佬，蓝奏云网盘里没2.1.1，下载地址在哪




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenhb23/lanzouyun-disk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月24日(星期天) 晚上8:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenhb23/lanzouyun-disk] 文件超过198M就无法上传，显示无法识别文件内容 (Issue #34)





 
可以试试 v2.1.1 新版本

**Comment by chenhb23** [comment]
忘传了！release 也有下载的

**Comment by chenhb23** [comment]
网盘也传好了

**Comment by Monokuma689** [comment]
谢谢大佬


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenhb23/lanzouyun-disk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月24日(星期天) 晚上9:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenhb23/lanzouyun-disk] 文件超过198M就无法上传，显示无法识别文件内容 (Issue #34)





 
网盘也传好了

**Comment by wonchong** [comment]
大佬辛苦了
