### ISSUE TITLE
可以增加文件夹上传，移动文件吗

### ISSUE THREAD

**Issue by ydhh** [chenhb23/lanzouyun-disk#36]
RT
1、直接拖拽文件夹上传
2、已上传文件批量移动

**Comment by chenhb23** [comment]
功能已加！

**Comment by ydhh** [comment]
太感谢了 =3=

**Comment by ydhh** [comment]
大佬 1/2功能测试均已成功，求增加
3、已上传的文件夹，支持多选   批量移动

**Comment by chenhb23** [comment]
3、4的功能也加上了，来，试一下吧

**Comment by ydhh** [comment]
太感谢了，真的是神仙大佬，天使大佬，测试过功能都成功了

**Comment by ydhh** [comment]
大佬如果下面这几个也能增加就好了
5、增加刷新页面按钮，或默认F5刷新页面
6、一键 支持多选  批量复制文件夹+文件的分享链接
7、一键 支持多选   修改文件夹+文件的分享密码

**Comment by ydhh** [comment]
感谢大佬 深夜更新，以上功能都实现拉，但是好像无法自动按顺序解析下载，因为蓝奏云地址解析后有一段时间的时效性，有时候下载多文件不方便晚上挂着下载
1、能否增加输入地址自动解析下载功能，解析完A下完，再开始解析B再开始下载
2、能否增加点击关闭按键，实际最小化到托盘

**Comment by chenhb23** [comment]
5的刷新就不做了，点击面包屑可达到相同效果

**Comment by chenhb23** [comment]
> 感谢大佬 深夜更新，以上功能都实现拉，但是好像无法自动按顺序解析下载，因为蓝奏云地址解析后有一段时间的时效性，有时候下载多文件不方便晚上挂着下载 1、能否增加输入地址自动解析下载功能，解析完A下完，再开始解析B再开始下载 2、能否增加点击关闭按键，实际最小化到托盘

这两个功能也加上了

**Comment by ydhh** [comment]
> 这两个功能也加上了

感谢大佬，大佬昨天突然被限制上传了，好像大概在22G左右，我看到您之前说一天8G也限制了，但是我记得当时1.0版本的时候好像有一天上传量比这个多，下个版本可不可以增加这2个功能
1、可选择上传任务数量，感觉只运行1个上传任务是否更能模拟真实上传情况
2、提示当天上传已经超出8G，软件自动限制不要进行上传（或者如果有准确数据） ，这条只是我个人想法，不知道能否实现HHH

**Comment by chenhb23** [comment]
有道理，可以安排上

**Comment by ydhh** [comment]
> 
感谢感谢 (*╯3╰)

**Comment by chenhb23** [comment]
功能已经加上去了

**Comment by ydhh** [comment]
> 功能已经加上去了

感谢感谢 马上去使用
