### ISSUE TITLE
软件没有默认的关闭窗口的图标啊啊

### ISSUE THREAD

**Issue by turboshi** [chenhb23/lanzouyun-disk#37]
能加上右上角的
![image](https://user-images.githubusercontent.com/67223445/165767568-561f9de3-7bfd-42c3-9061-7429dafd4e22.png)
的图标吗
每次alt f4我也……

**Comment by chenhb23** [comment]
app 是什么版本？

**Comment by turboshi** [comment]
不是最新的
谢谢
