### ISSUE TITLE
上传完后测试下载文件遇到错误！

### ISSUE THREAD

**Issue by lightoalawliet** [chenhb23/lanzouyun-disk#38]
文件大小：781MB
上传压缩格式：7Z，zip
问题场景：在下载此Data文件时遇到错误！无法进行下载！
提示错误信息：connect ECONNREFUSED 127.0.0.1:443
截图：
![1](https://user-images.githubusercontent.com/91387489/166087553-ab87062b-414f-417d-bf3b-24ab826eb5c3.jpg)

**Comment by chenhb23** [comment]
单个块能下载吗？

 <img width="1436" alt="iShot_2022-04-30_12 05 15" src="https://user-images.githubusercontent.com/74194963/166089919-6554c55c-72db-428a-a998-72ab23b8e386.png">

**Comment by chenhb23** [comment]
今天我也遇到这个问题了。出现这个错误的的原因就是文件被河蟹掉了，用浏览器下载不了

**Comment by chenhb23** [comment]
过段时间又可以下载，可能就是蓝奏云服务器抽了
