### ISSUE TITLE
建议增加/修改等功能

### ISSUE THREAD

**Issue by zuixiangsi** [chenhb23/lanzouyun-disk#39]
下载了最新版本，没有发现排序的功能，不知道是不是自己没整明白，能说明下如何排序吗？

另，希望文件全选后增加全部删除功能，否则文件多的情况给下一个一个删除挺费劲的。

**Comment by chenhb23** [comment]
点击标题就可以排序了，目前支持文件名和大小排序

**Comment by zuixiangsi** [comment]
> 

看到了，谢谢
