### ISSUE TITLE
文件过多时，会仅下载其中一部分

### ISSUE THREAD

**Issue by Olivia-K99** [chenhb23/lanzouyun-disk#4]
博主的软件非常好用，界面整洁，但目前使用当中还有一个很小的问题，链接当中的文件如果超过一定的数量，在网页当中就会被折叠。此时软件当中就仅能解析其中一部分，这个问题博主有考虑过解决吗？

**Comment by chenhb23** [comment]
以前没有这个问题的，最近蓝奏升级了一波接口，分享链接请求太快会导致失败，已经给了延迟请求了，所以解析速度会慢一点。

仅限制分享的链接，如果是自己的文件，解析速度不会有影响

1.0.3 已发！
