### ISSUE TITLE
Bug：有些文件上传后无法下载

### ISSUE THREAD

**Issue by zuixiangsi** [chenhb23/lanzouyun-disk#40]
有时候上传的文件无法下载，并不是所有文件，大概随机出现这种问题
![lanzou bug](https://user-images.githubusercontent.com/85442664/166218339-40f25c00-56e3-44fb-a0e0-17cb5e90dbf4.png)

**Comment by chenhb23** [comment]
这是蓝奏云的域名证书过期了，下载链接用浏览器打开也会有报警提示

**Comment by chenhb23** [comment]
发了最新的 2.3.0 版本，不管域名过不过期，都能下载文件

**Comment by zuixiangsi** [comment]
> 发了最新的 2.3.0 版本，不管域名过不过期，都能下载文件

好的
