### ISSUE TITLE
Bug：选择文件出现错误

### ISSUE THREAD

**Issue by zuixiangsi** [chenhb23/lanzouyun-disk#41]
比如文件路径如下

根目录 - 子目录 - 2个文件

我勾选上2个文件，在返回到子目录，把子目录打上勾，上面下载项会显示3个文件

https://user-images.githubusercontent.com/85442664/166232471-487beb73-b304-4af5-be05-cb6e566a883f.mp4

**Comment by chenhb23** [comment]
这是正常的！多选功能支持跨层级选择

批量移动功能目前 **只支持文件**，不支持文件夹，所以会把文件排除掉（排除了 `bug测试`，剩下2项）

批量下载则支持文件和文件夹，勾选了多少项，就会下载多少项（视频中会下载 `bug测试文件夹及文件夹下的2个文件`、`2.txt`、`1.txt`）

**Comment by zuixiangsi** [comment]
> 这是正常的！多选功能支持跨层级选择
> 
> 批量移动功能目前 **只支持文件**，不支持文件夹，所以会把文件夹排除掉（排除了 `bug测试`，剩下2项）
> 
> 批量下载则支持文件和文件夹，勾选了多少项，就会下载多少项（视频中会下载 `bug测试文件夹及文件夹下的2个文件`、`2.txt`、`1.txt`）

逻辑是这么个逻辑，不过的确有时候会让人蒙圈，有时候勾选了其他文件夹，忘记取消，还得挨个查看，就很头疼了

**Comment by chenhb23** [comment]
新增了文件夹批量移动功能，然后也把多选的逻辑修改了一下，仅支持当前层级多选，这样用起来就比较直观了

**Comment by zuixiangsi** [comment]
> 新增了文件夹批量移动功能，然后也把多选的逻辑修改了一下，仅支持当前层级多选，这样用起来就比较直观了

非常感谢
