### ISSUE TITLE
Bug：关于上传失败的问题

### ISSUE THREAD

**Issue by zuixiangsi** [chenhb23/lanzouyun-disk#42]
有时候上传文件已经显示100%，但是一直停留在这里无法成功，按后面的开始按钮重新上传有时候会成功（再次失败） ，有时候没有反应。
![上传bug](https://user-images.githubusercontent.com/85442664/166435994-be1823f4-eed9-4189-81a9-a2b8b5888adb.png)

**Comment by zuixiangsi** [comment]
看到了，是提示的这个错误。
![上传bug，错误提示](https://user-images.githubusercontent.com/85442664/166446755-0718f7d2-aa33-4ea9-a576-f8caef4d9b6a.png)

**Comment by chenhb23** [comment]
蓝奏云不支持上传 0xx 这种类型的文件。而且会有很明确的错误提示。
<img width="960" alt="image" src="https://user-images.githubusercontent.com/74194963/166455628-e353a847-5753-4aa6-bfc8-1ec691071356.png">

另外，0xx 的文件会被软件自动加上随机后缀，你的软件是修改过的吧

**Comment by zuixiangsi** [comment]
> 

没修改，是从你这里下载的，我是自己用7z把大文件压缩成的99M压缩分卷，压缩完就是“XXX.7z.随机数字”的格式
![Snipaste_2022-05-03_22-33-51](https://user-images.githubusercontent.com/85442664/166474076-b4230575-223e-475e-85e7-d82779cb7fc2.png)
![Snipaste_2022-05-03_22-37-07](https://user-images.githubusercontent.com/85442664/166474600-bd64ad3a-b466-40d9-8f36-78ab507311b6.png)

**Comment by chenhb23** [comment]
上传失败的后缀发一下，我测试看看

**Comment by zuixiangsi** [comment]
> 上传失败的后缀发一下，我测试看看

上传界面是不显示后缀的，只显示失败，如一楼的第一张图，这样，你找一个大点的文件（几个G的）压缩成分卷，然后批量上传测试应该就会遇到这种情况

**Comment by chenhb23** [comment]
现在还出现这个问题吗？

**Comment by zuixiangsi** [comment]
> 现在还出现这个问题吗？

我也不知道还有没有这问题，因为我这里等了5天了，还是无法上传的这个问题 #50 

显示上传百分百，还是卡在“正上传中”，我都怀疑不是被限制了，是被“隐性封号了”吧……
![Snipaste_2022-05-15_21-52-10](https://user-images.githubusercontent.com/85442664/168476549-b270f3ed-c797-473c-b04d-70df6347b3e5.png)
