### ISSUE TITLE
最新版本不能上传大于100m的文件了吗？

### ISSUE THREAD

**Issue by linhaibuaichixiangcai** [chenhb23/lanzouyun-disk#43]
![屏幕截图(105)](https://user-images.githubusercontent.com/102218069/166493148-cb1e9b14-035a-4163-b6f1-c7e2ca5fe0d3.png)

**Comment by chenhb23** [comment]
大文件上传功能已经关闭了，如果要用，可以把项目 fork 下来自行修改。

或者使用自带文件分割功能或压缩软件进行分卷，然后手动上传。

**Comment by acdc126** [comment]
分割了怎么合并呀！

**Comment by chenhb23** [comment]
上传到同名文件夹（带文件后缀），然后下载文件夹就自动合并了

**Comment by acdc126** [comment]
谢谢！
