### ISSUE TITLE
上传和下载文件加上完成进度条

### ISSUE THREAD

**Issue by lightoalawliet** [chenhb23/lanzouyun-disk#45]
在上传和下载文件的时候，在显示百分比的基础上添加进度条的视图呈现效果会给用户更直观的使用体验，就像百度云盘在上传或下载文件时呈现出带有进度条的百分比视图一样：
![1](https://user-images.githubusercontent.com/91387489/166648628-6f33ca48-1c95-4063-9d50-5374e7312f64.jpg)

**Comment by lightoalawliet** [comment]
不知道作者之后会把进度条给加上吗？这对于云盘的上传下载的直观体验上来说还是挺重要的！

**Comment by chenhb23** [comment]
已经加上了

**Comment by lightoalawliet** [comment]
好耶！
