### ISSUE TITLE
建议功能：增加下载位置询问

### ISSUE THREAD

**Issue by zuixiangsi** [chenhb23/lanzouyun-disk#46]
在保存设置默认下载路径的同时，希望增加下载文件时询问下载位置，这样同时下载多个不同文件需要保存到不同的位置就很方便了。

**Comment by LOVEgithub12** [comment]
好的，明天就加

**Comment by zuixiangsi** [comment]
建议增加：上传下载速度 **xxx/秒**

**Comment by chenhb23** [comment]
询问下载地址功能已经加上了，上传下载速度还得等等

**Comment by chenhb23** [comment]
> 建议增加：上传下载速度 **xxx/秒**

已经加上了

**Comment by zuixiangsi** [comment]
> > 建议增加：上传下载速度 **xxx/秒**
> 
> 已经加上了

Good！
