### ISSUE TITLE
画了一个 logo 给老哥

### ISSUE THREAD

**Issue by d1y** [chenhb23/lanzouyun-disk#48]
用 `logoist 4` 画的

![lanzou](https://user-images.githubusercontent.com/45585937/167293625-1601e7c0-a014-46ff-b313-6e38c5a7ac7e.png)

老哥可以接受PR吗

**Comment by chenhb23** [comment]
老哥你来晚一步，但还是感谢提供！这几天没有更新 app，一是在升级 3.0 版本，新增暗黑模式；另外就是自己在捣鼓图标😄。今天已经封版了，就是右下角那个（有什么可以改进的欢迎提出🙈）。

<img width="981" alt="image" src="https://user-images.githubusercontent.com/74194963/167293879-e6d351c0-a9dc-4ce6-9376-50630d0b23f5.png">

<img width="923" alt="image" src="https://user-images.githubusercontent.com/74194963/167294082-b1951441-0167-4c48-83f8-dbd861dc2dd0.png">

**Comment by wonchong** [comment]
再画个盒子，图吧丢盒子里面，意味着“安装包”。做成自解压吧。
![image](https://user-images.githubusercontent.com/82252714/167303215-cc1bdac0-fd3e-4ae7-9bc6-5297ae9591a1.png)

**Comment by lightoalawliet** [comment]
@chenhb23 还是你选择的图标看着好看，我看其它人的图标都不好看，从这点可以看出来，作者也是一个完美主义者！

**Comment by ydhh** [comment]
@chenhb23 辛苦大佬拉 捶肩
