### ISSUE TITLE
刚开始用 ，请问分割后的文件下载下来后怎样合并？

### ISSUE THREAD

**Issue by Michael-J-ScofieldOVO** [chenhb23/lanzouyun-disk#49]
刚开始用 ，请问分割后的文件下载下来后怎样合并？

**Comment by chenhb23** [comment]
https://github.com/chenhb23/lanzouyun-disk/issues/43#issuecomment-1119555813

**Comment by Michael-J-ScofieldOVO** [comment]
> [#43 (comment)](https://github.com/chenhb23/lanzouyun-disk/issues/43#issuecomment-1119555813)

感谢~
