### ISSUE TITLE
jpg图片格式打.zip压缩包后无法上传到蓝奏云客户端

### ISSUE THREAD

**Issue by lightoalawliet** [chenhb23/lanzouyun-disk#51]
蓝奏云客户端版本：3.0.0.0
问题场景：jpg格式的图片文件打.zip的压缩包后，无法上传到蓝奏云的客户端当中
如图所示：
![1](https://user-images.githubusercontent.com/91387489/167360247-e05560a0-acb3-424c-b550-b5e92cbbbafa.jpg)

**Comment by JXTang-syc** [comment]
文件<100M?

**Comment by lightoalawliet** [comment]
@JXTang-syc 文件大小是175M

**Comment by lightoalawliet** [comment]
@chenhb23 那什么时间能恢复上传大于100以上的文件呢？

**Comment by lightoalawliet** [comment]
老版本的蓝奏云客户端还能不能上传大于100m的文件了呢？
新版本什么时候能再能上传大于100m的文件呢？

chenhb23 ***@***.***> 於 2022年5月9日週一 下午9:10寫道：
