### ISSUE TITLE
无法解析链接

### ISSUE THREAD

**Issue by weiter0** [chenhb23/lanzouyun-disk#53]
不知道是哪里出了问题，别人分享的下载链接。

2.0.0版本的也无法解析，显示这个。
![image](https://user-images.githubusercontent.com/88627186/168294759-4e9b2324-6134-4f2d-ac2b-32a3b3e7be97.png)

3.0.3版本的也无法解析，点击解析没有反应。

**Comment by chenhb23** [comment]
链接提供一下

**Comment by chenhb23** [comment]
另外，请确保链接在浏览器上是可以正常打开的

**Comment by chenhb23** [comment]
这好像是会员链接，我适配一下

**Comment by FYdz99** [comment]
> 浏览器可以打开 https://xiyoufuman.lanzouf.com/b0172ka8j 提取码：9hxn

同道中人啊，可以用这个当备用，https://www.lanzouf.com/b02c4d88d 密码:zfg
我刚发现的，粗糙但蛮好用的

**Comment by chenhb23** [comment]
> 不知道是哪里出了问题，别人分享的下载链接。
> 
> 2.0.0版本的也无法解析，显示这个。 ![image](https://user-images.githubusercontent.com/88627186/168294759-4e9b2324-6134-4f2d-ac2b-32a3b3e7be97.png)
> 
> 3.0.3版本的也无法解析，点击解析没有反应。

搞好了，可以试一下

**Comment by weiter0** [comment]
好了耶( •̀ ω •́ )y    大佬辛苦啦❤b(￣▽￣)d    晚安(￣o￣) . z Z
