### ISSUE TITLE
三点建议

### ISSUE THREAD

**Issue by wonchong** [chenhb23/lanzouyun-disk#54]
1、期待最小化到托盘。很多时候点击关闭按钮并不是想退出它，而是想让它托盘运行。
2、期待暗黑模式的保持。现在暗黑模式点击关闭按钮后，再打开则自动恢复为浅色模式。
3、建议拒绝重复运行。如果重复运行，则弹窗提示。
![1](https://user-images.githubusercontent.com/82252714/168374882-c6d45575-5a40-410d-be3c-4ad1661a169b.png)

**Comment by chenhb23** [comment]
重复运行是指多开吗

**Comment by chenhb23** [comment]
功能已经加上了

**Comment by wonchong** [comment]
- [ ] 

> 重复运行是指多开吗

对，这是一种弹窗参考
![image](https://user-images.githubusercontent.com/82252714/168437891-36c92f65-9008-480d-968c-fae0a6c4e6f4.png)

**Comment by chenhb23** [comment]
变成任务栏的小图标了，右键小图标退出

**Comment by wonchong** [comment]
谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月14日(星期六) 晚上11:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chenhb23/lanzouyun-disk] 三点建议 (Issue #54)





 
变成任务栏的小图标了，右键小图标退出
