### ISSUE TITLE
实操问题反馈及优化建议

### ISSUE THREAD

**Issue by Kenny-Bob** [chenhb23/lanzouyun-disk#55]
问题反馈：
1、文件分割上传问题：目前文件可以正常分割，但是上传过程中除第一个文件上传成功之外，其它文件上传到100%后系统提示：无法识别文件内容，请联系客服处理。最终结果，上传失败。失败率较高。

2、文件合并功能缺失：即便上传成功，但是文件下载合并恢复原文件，失去可读性问题严重。解析下载功能有自动合并，但是合并后的文件无法恢复原文件失去可读性，导致功能项失去意义，形同虚设，另外，勾选所有子文件后，自动合并功能无法勾选，若直接点解解析下载，下载后的文件并非原文件格式，主动修改会提示文件已损坏。如有正确操作方法，请告知，谢谢。

优化建议：
1、文件分割功能优化：增加自定义分割文件大小及文件名（主名+扩展名）

2、增加文件合并功能：使下载下来的分割文件快速有效合并恢复原文件，保证文件的可读性。

备注：使用软件版本lanzouyun-3.3.0-x64-win

**Comment by chenhb23** [comment]
### 1

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/74194963/168557084-61fc0dec-3d59-4178-b5c7-900f0d2e8e95.png">
昨天进行过连续上传，没有发现失败的情况。可能官方加了新的文件检测，可以反馈一下上传失败的文件后缀。

### 2

如果不是下载全部文件，自动合并出来的文件也是损坏的，所以下载部分文件的话，就把自动合并给禁掉了

现在拿到源文件有两种方法：
1. 解析 URL 页面的 下载全部+自动合并 操作；
2. 所有分块上传到带后缀的文件夹，下载带后缀的文件夹就可以得到源文件 https://github.com/chenhb23/lanzouyun-disk/issues/43#issuecomment-1119555813

**Comment by chenhb23** [comment]
分割合并都加上了

**Comment by Kenny-Bob** [comment]
> ### 1
> <img alt="image" width="1010" src="https://user-images.githubusercontent.com/74194963/168557084-61fc0dec-3d59-4178-b5c7-900f0d2e8e95.png">
> 
> 昨天进行过连续上传，没有发现失败的情况。可能官方加了新的文件检测，可以反馈一下上传失败的文件后缀。
> ### 2
> 如果不是下载全部文件，自动合并出来的文件也是损坏的，所以下载子文件的话（不管是不是全选了文件），就把自动合并给禁掉了
> 
> 现在拿到源文件有两种方法：
> 
> 1. 解析 URL 页面的 下载全部+自动合并 操作；
> 2. 所有分块上传到带后缀的文件夹，下载带后缀的文件夹就可以得到源文件 [最新版本不能上传大于100m的文件了吗？ #43 (comment)](https://github.com/chenhb23/lanzouyun-disk/issues/43#issuecomment-1119555813)

感谢大神解疑答惑，谢谢

**Comment by Kenny-Bob** [comment]
> 分割合并都加上了

新版已使用，感觉不错，感谢大神采纳优化建议，大神辛苦啦
