### ISSUE TITLE
文件分割问题

### ISSUE THREAD

**Issue by TT-IPIP** [chenhb23/lanzouyun-disk#58]
我的是 单个文件大小 200mb
分割自动是99mb 
可以设置自定义分割大小吗
或者弄2个选项一个99mb一个199mb

**Comment by wonchong** [comment]
![image](https://user-images.githubusercontent.com/82252714/170196541-e507de6e-64b9-466b-a056-a8256324134f.png)
我一般是用压缩软件先分卷打包成.7z.001 .7z.002 然后再针对每个打包文件再分别单独打包一次并再分享的适合特别说明。

**Comment by chenhb23** [comment]
> 我的是 单个文件大小 200mb 分割自动是99mb 可以设置自定义分割大小吗 或者弄2个选项一个99mb一个199mb

功能加上了

**Comment by TT-IPIP** [comment]
感谢
