### ISSUE TITLE
不能像以前一样上传大小超过100m的文件

### ISSUE THREAD

**Issue by lightoalawliet** [chenhb23/lanzouyun-disk#60]
我记得以前蓝奏云客户端是可以直接上传大小超过100m的文件的，
但现在却不可以直接上传只能文件分割了，感觉没有以前方便快捷了，
不知道以后还能不能直接上传文件大小超过100m的文件？
是不是开发者正在解决这个问题？

**Comment by chenhb23** [comment]
一开始用户少，软件本着学习交流的目的，不限制功能。

现在用户量增多，**直接** 上传大文件的功能，不适于大范围使用了（毕竟上传大文件是蓝奏唯一的收费功能，有能力的可以 fork 下来注释掉限制文件大小的代码即可）。

分割成小文件后就不同了，因为上传的是允许大小范围内的文件！
