### ISSUE TITLE
解析URL优化

### ISSUE THREAD

**Issue by gongsunxun** [chenhb23/lanzouyun-disk#7]
希望能把文件分享和解析URL联动，使得粘贴文件分享链接时自动将链接里的密码填写到后面。

**Comment by chenhb23** [comment]
1.0.7 版本已支持该功能

**Comment by gongsunxun** [comment]
> 1.0.7 版本已支持该功能

新版是还没出Windows吗？我只看到了MAC版

**Comment by chenhb23** [comment]
win版已上传，压缩包改成了zip的格式
