### ISSUE TITLE
Big Sur没有办法打开……

### ISSUE THREAD

**Issue by Olivia-K99** [chenhb23/lanzouyun-disk#8]
求助，升级了macos big sur之后一直显示没有权限打开文件，如下所示

“您没有权限来打开应用程序“蓝奏云盘”。

**Comment by chenhb23** [comment]
请尝试如下办法：

1. 在安全与隐私中允许打开app
2. 尝试使用 1.0.7 版本

**Comment by Olivia-K99** [comment]
Problem solved, thanks!
