### ISSUE TITLE
文件上传后缀篡改

### ISSUE THREAD

**Issue by furxt** [chenhb23/lanzouyun-disk#83]
上传.gz压缩包时文件后缀就会被篡改
上传的文件如下：
![image](https://user-images.githubusercontent.com/106371610/195551937-f7f0c680-86a4-498c-98d2-4236ef2841ad.png)
上传之后的文件：
![image](https://user-images.githubusercontent.com/106371610/195552211-e0b4678a-3b25-4b90-9a82-15be350112ea.png)

**Comment by chenhb23** [comment]
gz 是不支持的文件格式，会自动添加后缀，然后再上传。下载后会自动还原后缀名

**Comment by furxt** [comment]
首先感谢作者的回复，但是实际情况并非如此！
如下：
![image](https://user-images.githubusercontent.com/106371610/195749058-2427f037-df89-49ed-972b-f033324aede6.png)
![image](https://user-images.githubusercontent.com/106371610/195749174-f9728695-4152-4de1-8a05-1f5aca2d6f7b.png)
再次感谢作者的回复！

**Comment by chenhb23** [comment]
确实是个 bug，新版已修复
