### ISSUE TITLE
没法自定义安装路径

### ISSUE THREAD

**Issue by ShuiRen77** [chenhb23/lanzouyun-disk#9]
没法自定义安装路径，装C盘感觉很不舒服，先收藏了。

**Comment by chenhb23** [comment]
往后不提供 setup 安装包了，可解压 zip 到自己想安装的位置

**Comment by ShuiRen77** [comment]
> 往后不提供安装安装包了，可解压zip到自己想安装的位置

安装包加一个自定义安装不是更好吗
