### ISSUE TITLE
关于文件消失，变成请忽使用第三方工具这件事

### ISSUE THREAD

**Issue by HONE13** [chenhb23/lanzouyun-disk#98]
![33](https://user-images.githubusercontent.com/54649543/210978555-9333a1bc-2e81-43e7-aeeb-81fd5f6d370f.png)

**Comment by 3259262183** [comment]
情况+1，同类型软件lanzou-gui也是，并且报毒

**Comment by pretyboymzc** [comment]
情况+1

**Comment by Michael-Zyx** [comment]
情况+1

**Comment by Jeeesees** [comment]
+1

**Comment by Jeeesees** [comment]
down到本地之后改回原文件后缀是可以用的

**Comment by aoaoemoji** [comment]
这官方真的是玩不起

**Comment by cly312** [comment]
+1，但是下载下来的文件改个文件名+后缀还是正常

**Comment by miaomjn** [comment]
情况+1

**Comment by miaomjn** [comment]
> +1，但是下载下来的文件改个文件名+后缀还是正常

情况+1

**Comment by chenhb23** [comment]
已修复

**Comment by aoaoemoji** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Yuer6327** [comment]
+1，但是回收站看起来是正常的
