### ISSUE TITLE
上传后，软件内的文件名会被更改，提取分享码后，也是更改的文件名

### ISSUE THREAD

**Issue by kissmemory** [chenhb23/lanzouyun-disk#99]
![图片](https://user-images.githubusercontent.com/55163754/211198171-0fe90e34-beb3-4cca-87cf-df3a141bf066.png)

**Comment by Jeeesees** [comment]
+1

**Comment by cly312** [comment]
+1

**Comment by xusos** [comment]
+1

**Comment by chenhb23** [comment]
已修复

**Comment by xusos** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
